# Find more information on toml format here:  https://github.com/toml-lang/toml
modLoader="javafml"
loaderVersion="[28,)"
logoFile="walljump.png"
[[mods]]
modId="walljump"
version="1.15.2-1.3.3"
displayName="Wall-Jump!"
displayURL="https://www.curseforge.com/minecraft/mc-mods/wall-jump"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/wall-jump/issues"
authors="genandnic"
description="Jump from wall to wall!
Jump towards a wall and hold the wall jump key (LSHIFT).
Then while wall clinging, keep holding W and let go of LSHIFT to wall jump."
